import * as SQLite from "expo-sqlite";


//Types
export type ZoneConfig = {
  powerLevel: number;
  frequencyHz: number;
};

export type Protocol = {
  id: number;              // uuid
  name: string;
  timeMin: number;
  timeSec: number;
  Zones: Record<number, ZoneConfig>; // Each Zones holds holds a config(powerLevel, frequencyHz)
};


// Database init
let db: SQLite.SQLiteDatabase | null = null;

export async function getDb(): Promise<SQLite.SQLiteDatabase> {
  if (!db) db = await SQLite.openDatabaseAsync("ProtocolsDB.db");
  return db;
}

export async function initDb() {
  const db = await getDb();
  await db.execAsync(`
    PRAGMA foreign_keys = ON;
    PRAGMA journal_mode = WAL;

    DROP TABLE IF EXISTS protocols;
    CREATE TABLE IF NOT EXISTS protocols (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      time_min INTEGER NOT NULL,
      time_sec INTEGER NOT NULL,
      zones_json TEXT NOT NULL
    );
  `);
  return db;
}


// Store Protocol
export async function storeProtocol(
  p: Pick<Protocol, "name" | "timeMin" | "timeSec" | "Zones">
): Promise<number> {
  const db = await getDb();
  const zonesJson = JSON.stringify(p.Zones ?? {});

  const result = await db.runAsync(
    `INSERT INTO protocols (name, time_min, time_sec, zones_json)
     VALUES (?, ?, ?, ?);`,
    [p.name, p.timeMin, p.timeSec, zonesJson]
  );

  return result.lastInsertRowId; // numeric id generated by SQLite
}

export async function seedProtocols() {
  const db = await getDb();

  const protocols = [
    {
      name: "Memory Boost",
      timeMin: 30,
      timeSec: 0,
      Zones: {
        1: { powerLevel: 50, frequencyHz: 10 },
        2: { powerLevel: 50, frequencyHz: 10 },
        3: { powerLevel: 50, frequencyHz: 10 },
        4: { powerLevel: 50, frequencyHz: 10 },
        5: { powerLevel: 50, frequencyHz: 10 },
        6: { powerLevel: 50, frequencyHz: 10 },
        7: { powerLevel: 50, frequencyHz: 10 },
        8: { powerLevel: 50, frequencyHz: 10 },
        9: { powerLevel: 50, frequencyHz: 10 },
        10: { powerLevel: 50, frequencyHz: 10 },
        11: { powerLevel: 50, frequencyHz: 10 },
        12: { powerLevel: 50, frequencyHz: 10 },
      },
    },
    {
      name: "Brain Boost",
      timeMin: 30,
      timeSec: 0,
      Zones: {
        1: { powerLevel: 55, frequencyHz: 12 },
        2: { powerLevel: 55, frequencyHz: 12 },
        3: { powerLevel: 55, frequencyHz: 12 },
        4: { powerLevel: 55, frequencyHz: 12 },
        5: { powerLevel: 55, frequencyHz: 12 },
        6: { powerLevel: 55, frequencyHz: 12 },
        7: { powerLevel: 55, frequencyHz: 12 },
        8: { powerLevel: 55, frequencyHz: 12 },
        9: { powerLevel: 55, frequencyHz: 12 },
        10: { powerLevel: 55, frequencyHz: 12 },
        11: { powerLevel: 55, frequencyHz: 12 },
        12: { powerLevel: 55, frequencyHz: 12 },
      },
    },
    {
      name: "Health Boost",
      timeMin: 30,
      timeSec: 0,
      Zones: {
        1: { powerLevel: 60, frequencyHz: 8 },
        2: { powerLevel: 60, frequencyHz: 8 },
        3: { powerLevel: 60, frequencyHz: 8 },
        4: { powerLevel: 60, frequencyHz: 8 },
        5: { powerLevel: 60, frequencyHz: 8 },
        6: { powerLevel: 60, frequencyHz: 8 },
        7: { powerLevel: 60, frequencyHz: 8 },
        8: { powerLevel: 60, frequencyHz: 8 },
        9: { powerLevel: 60, frequencyHz: 8 },
        10: { powerLevel: 60, frequencyHz: 8 },
        11: { powerLevel: 60, frequencyHz: 8 },
        12: { powerLevel: 60, frequencyHz: 8 },
      },
    },
  ];

  for (const p of protocols) {
    const zonesJson = JSON.stringify(p.Zones);
    await db.runAsync(
      `INSERT INTO protocols (name, time_min, time_sec, zones_json)
       VALUES (?, ?, ?, ?);`,
      [p.name, p.timeMin, p.timeSec, zonesJson]
    );
  }

  console.log("Seeded default protocols");
}
